### ISSUE TITLE
pyubx2 stop processing when there is a broken data in the ubx file.

### ISSUE THREAD

**Issue by yang-neu** [semuconsulting/pyubx2#109]
May I ask for your assistance with regard to an issue I am encountering? 
It appears that when there is broken data in the UBX file, the program Pyubx2 raises an exception and stops processing. 
The error message associated with this exception is "'str' object has no attribute 'dict'". 
I have noticed that this issue persists even with the latest version 1.2.23.

I kindly request your help in addressing this issue. 
Would it be possible to continue the procedure despite the error data by simply displaying some messages? 
For your information, my operating system is Windows 10 and I am recording logs via U-center v22.05. 
The device model I am using is the u-blox NEO-9M, and the protocol in use is UBX_PROTOCOL.

Thank you for your attention to this matter. I sincerely appreciate any response or assistance you can provide.

**Comment by semuadmin** [comment]
HI @yang-neu 

Please provide the FULL TRACEBACK of the error message you're getting and, if possible, a copy of the UBX file you're trying to process. Thank you.

**Comment by semuadmin** [comment]
No worries. More than happy to consider any enhancements that may make life easier.
