### ISSUE TITLE
Correct is diffSoln, no difSoln

### ISSUE THREAD

**Issue by klepo** [semuconsulting/pyubx2#152]
https://github.com/semuconsulting/pyubx2/blob/b9da2f67694959b65d13444b41bd3b07032c66b3/src/pyubx2/ubxtypes_get.py#L2432

**Comment by semuadmin** [comment]
Hi @klepo 

Sorry - what specifically is the issue here?  I'll need a lot more information than this.

**Comment by semuadmin** [comment]
OK typo will be fixed in next release, but the attribute can still be referenced now as msg.difSoln in the meantime.
