### ISSUE TITLE
streamer exemple using asyncio. Or maybe UBXReader.read() alternative

### ISSUE THREAD

**Issue by Hadatko** [semuconsulting/pyubx2#34]
**Is your feature request related to a problem? Please describe.**

Hello, when we started to use this module we got inspire with your examples. For reading data we looked into stremear example. This solution was eating 100% cpu when we were not waiting any data (most of the time => period 5min). 

**Describe the solution you'd like**

So we decided to do solution with asyncio. We have solution for our case. SO we were thinking that we can share example. Maybe  it can get into core of module but i think it is not that quality currently. 

**Additional context**

We were curious if you would accept such an example.

**Comment by semuadmin** [comment]
Many thanks for this. The streamer example provided is indeed very simple. It serves its purpose but, as you say, is resource-heavy and not suitable for any production context. If you would care to post your asyncio example here (or a link to it on GitHub) we'd be more than happy to take a look at it. Cheers!

**Comment by semuadmin** [comment]
@Hadatko I'll close this for now but by all means submit a PR if you have a useful improvement or example and we'll happily review it. Cheers
