### ISSUE TITLE
GPS-UTC Offset

### ISSUE THREAD

**Issue by martinty** [semuconsulting/pyubx2#45]
Version: `1.2.0`
File: `pyubx2/pyubx2/ubxhelpers.py`

I think the offset between iTOW and UTC is 2 seconds off? It should be 18 seconds and not 16 seconds. 

From <https://endruntechnologies.com/support/leap-seconds>.
- TAI-UTC = 37 seconds
- GPS-UTC = 18 seconds
- TAI-GPS = 19 seconds

```py
def itow2utc(itow: int) -> datetime.time:
    """
    Convert GPS Time Of Week to UTC time.
    :param int itow: GPS Time Of Week
    :return: UTC time hh.mm.ss
    :rtype: datetime.time
    """

    utc = datetime(1980, 1, 6) + timedelta(seconds=(itow / 1000) - (35 - 19))   #Fix: 37 - 19 = 18
    return utc.time()
```

**Comment by semuadmin** [comment]
Good spot, thanks.
