### ISSUE TITLE
CircleCI automation 

### ISSUE THREAD

**Issue by Hadatko** [semuconsulting/pyubx2#59]
**Is your feature request related to a problem? Please describe.**

Hi, you may consider using circleci auto free run test with every PR. They will be executed automaticly on PR creation and change and you may be sure that code is properly tested.

**Describe the solution you'd like**

-

**Describe alternatives you've considered**

Any other automation system

**Would you be willing to assist with testing?**

Sure no problem :D I did same for eRPC. You can see it e.g. here https://github.com/EmbeddedRPC/erpc/pull/254 at bottom (all checks passed).

**Additional context**

**Comment by semuadmin** [comment]
Hi @Hadatko Thanks but no thanks. 

I prefer to avoid any reliance on proprietary automation tooling, having been bitten by various continuity/support issues in the past, and (_for the time being at least_) the volume of changes the library is handling doesn't really warrant it. I'm already leveraging automated GitHub Actions workflows in conjunction with a comprehensive UnitTest suite which provides 100% code coverage.
