### ISSUE TITLE
webserver example not working

### ISSUE THREAD

**Issue by jancelin** [semuconsulting/pyubx2#62]
Hello,

[pyubx2 v1.26] [F9P]

I can't get the webserver example to work...

I added a line ``print(parsed_data)`` on [line 166](https://github.com/semuconsulting/pyubx2/blob/master/examples/webserver/ubxserver.py) to better illustrate my problem
Here is what happens when I start the service

```
python3 ubxserver.py 
Connecting to serial port /dev/pts/2 at 115200 baud...

Starting serial read thread...

Starting HTTP Server on http://127.0.0.1:8123 ...
Press Ctrl-C to terminate.

<UBX(NAV-PVT, iTOW=14:37:23, year=2022, month=4, day=11, hour=14, min=37, second=23, validDate=1, validTime=1, fullyResolved=1, validMag=0, tAcc=21, nano=32824, fixType=3, gnssFixOk=1, difSoln=1, psmState=0, headVehValid=0, carrSoln=1, confirmedAvai=1, confirmedDate=1, confirmedTime=1, numSV=19, lon=-1.0281844, lat=45.9921417, height=55272, hMSL=7149, hAcc=14, vAcc=11, velN=5, velE=3, velD=-5, gSpeed=6, headMot=307.36934, sAcc=83, headAcc=180.0, pDOP=1.28, invalidLlh=0, lastCorrectionAge=0, reserved0=1044519020, headVeh=0.0, magDec=0.0, magAcc=0.0)>
Something went wrong Message checksum b'\x00\x00' invalid - should be b'\xab\t'
<UBX(RXM-SFRBX, gnssId=Galileo, svId=30, reserved0=1, freqId=0, numWords=9, chn=49, version=2, reserved1=208, dwrd_01=172157743, dwrd_02=3776755709, dwrd_03=3154092032, dwrd_04=2231468032, dwrd_05=3003596800, dwrd_06=42, dwrd_07=2863297454, dwrd_08=3112124416, dwrd_09=0)>
<UBX(RXM-SFRBX, gnssId=Galileo, svId=36, reserved0=1, freqId=0, numWords=9, chn=20, version=2, reserved1=216, dwrd_01=174254895, dwrd_02=3777549821, dwrd_03=3154092032, dwrd_04=2231468032, dwrd_05=3003605611, dwrd_06=2734180266, dwrd_07=2863292447, dwrd_08=1249853440, dwrd_09=0)>
Something went wrong Message checksum b'\x00\x00' invalid - should be b'J\x0b'
<UBX(RXM-SFRBX, gnssId=GPS, svId=23, reserved0=0, freqId=0, numWords=10, chn=1, version=2, reserved1=0, dwrd_01=583048449, dwrd_02=2337352243, dwrd_03=1006485321, dwrd_04=2347592695, dwrd_05=621987212, dwrd_06=1041481844, dwrd_07=47615079, dwrd_08=37660748, dwrd_09=57217316, dwrd_10=147464095)>
<UBX(RXM-SFRBX, gnssId=GPS, svId=29, reserved0=0, freqId=0, numWords=10, chn=3, version=2, reserved1=32, dwrd_01=583048449, dwrd_02=2337352243, dwrd_03=75589508, dwrd_04=176016204, dwrd_05=1022468931, dwrd_06=18268243, dwrd_07=42600581, dwrd_08=2229971034, dwrd_09=2205569994, dwrd_10=2294925823)>
<UBX(RXM-SFRBX, gnssId=GLONASS, svId=10, reserved0=0, freqId=0, numWords=4, chn=13, version=2, reserved1=32, dwrd_01=1707355723, dwrd_02=3329273952, dwrd_03=282068992, dwrd_04=65470469)>
<UBX(RXM-SFRBX, gnssId=GLONASS, svId=20, reserved0=0, freqId=9, numWords=4, chn=30, version=2, reserved1=32, dwrd_01=1707355723, dwrd_02=3329273952, dwrd_03=282068992, dwrd_04=65470469)>
<UBX(RXM-SFRBX, gnssId=GLONASS, svId=20, reserved0=2, freqId=9, numWords=4, chn=101, version=2, reserved1=64, dwrd_01=1707355723, dwrd_02=3329273952, dwrd_03=282068992, dwrd_04=65470469)>
<UBX(RXM-SFRBX, gnssId=GLONASS, svId=11, reserved0=0, freqId=7, numWords=4, chn=17, version=2, reserved1=32, dwrd_01=1707355723, dwrd_02=3329273952, dwrd_03=282068992, dwrd_04=65470469)>
<UBX(RXM-SFRBX, gnssId=GLONASS, svId=11, reserved0=2, freqId=7, numWords=4, chn=100, version=2, reserved1=64, dwrd_01=1707355723, dwrd_02=3329273952, dwrd_03=282068992, dwrd_04=65470469)>
<UBX(RXM-SFRBX, gnssId=Galileo, svId=36, reserved0=5, freqId=0, numWords=8, chn=64, version=2, reserved1=64, dwrd_01=9786709, dwrd_02=1431655765, dwrd_03=1431655765, dwrd_04=1383366656, dwrd_05=2278359040, dwrd_06=42, dwrd_07=2863309660, dwrd_08=1568620544)>
<UBX(RXM-SFRBX, gnssId=Galileo, svId=30, reserved0=5, freqId=0, numWords=8, chn=75, version=2, reserved1=64, dwrd_01=9786709, dwrd_02=1431655765, dwrd_03=1431655765, dwrd_04=1383366656, dwrd_05=2278359040, dwrd_06=42, dwrd_07=2863309660, dwrd_08=1568620544)>
<UNKNOWN PROTOCOL(header=b'$w')>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/basegnss/pyubx2/examples/webserver/ubxserver.py", line 167, in set_data
    if parsed_data.identity == 'NAV-PVT':
AttributeError: 'str' object has no attribute 'identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/basegnss/pyubx2/examples/webserver/ubxserver.py", line 150, in _read_thread
    self.set_data(parsed_data)
  File "/home/basegnss/pyubx2/examples/webserver/ubxserver.py", line 192, in set_data
    except ube.UBXMessageError() as err:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

[F9P_rover_usb_uart1-RAWX_SFRBX_PVT.txt](https://github.com/semuconsulting/pyubx2/files/8465134/F9P_rover_usb_uart1-RAWX_SFRBX_PVT.txt)

**Comment by Hadatko** [comment]
Hello
`except ube.UBXMessageError() as err:` should be `except ube.UBXMessageError as err:` ??

**Comment by jancelin** [comment]
Hi @Hadatko ,
same problem but cleaner without the ()

```Connecting to serial port /dev/pts/2 at 115200 baud...

Starting serial read thread...

Starting HTTP Server on http://127.0.0.1:8123 ...
Press Ctrl-C to terminate.

<UBX(NAV-PVT, iTOW=15:17:25, year=2022, month=4, day=11, hour=15, min=17, second=25, validDate=1, validTime=1, fullyResolved=1, validMag=0, tAcc=1006, nano=155037, fixType=3, gnssFixOk=1, difSoln=1, psmState=0, headVehValid=0, carrSoln=2, confirmedAvai=1, confirmedDate=1, confirmedTime=1, numSV=21, lon=-1.0281327, lat=45.9921395, height=50492, hMSL=2369, hAcc=36, vAcc=50, velN=6, velE=-13, velD=-11, gSpeed=14, headMot=116.17642, sAcc=99, headAcc=180.0, pDOP=1.21, invalidLlh=0, lastCorrectionAge=0, reserved0=1044519020, headVeh=0.0, magDec=0.0, magAcc=0.0)>
Something went wrong Message checksum b'\x00\x1a' invalid - should be b'\x8e\x84'
<UNKNOWN PROTOCOL(header=b'$\x00')>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/basegnss/pyubx2/examples/webserver/ubxserver.py", line 150, in _read_thread
    self.set_data(parsed_data)
  File "/home/basegnss/pyubx2/examples/webserver/ubxserver.py", line 167, in set_data
    if parsed_data.identity == 'NAV-PVT':
AttributeError: 'str' object has no attribute 'identity'
```

**Comment by jancelin** [comment]
Hi

It's OK, it works on my side. Thanks a lot!

I use str2str to inject RTCM3 data for RTK [centipede.fr](https://centipede.fr), so I'm going to modify the web interface a bit to have all the PVT information on the precision of hAcc, vAcc, carrSoln data,...
it's for the [physalia](https://github.com/jancelin/physalia) and [Rtkbase](https://github.com/Stefal/rtkbase) project, 
I'll share my progress.

![Screenshot 2022-04-12 at 11-15-26 GPS Server Demo](https://user-images.githubusercontent.com/6421175/162925749-b9fb64fc-829f-4faa-9b56-a0bd700b5cb9.png)

**Comment by semuadmin** [comment]
OK glad the web server example works OK, and if it provides a useful basis for your own project then great! It's easy enough to amend the `set_data()` routine to accept other incoming data sources (including NMEA and RTCM3 if needs be). Do please share progress - thanks.

Just bear in mind that this is a fairly simplistic web server implementation; please heed the warning on the [http.server library home page](https://docs.python.org/3/library/http.server.html):

<img width="400" alt="http server warning" src="https://user-images.githubusercontent.com/28569967/162928942-f06224e3-16cc-4588-8097-9dd96067b7a9.png">

Out of interest, did you actually get to the bottom of the 'invalid checksum' and 'UNKNOWN PROTOCOL' errors? `pyubx2` should be capable of handling any of the protocols output by a u-blox device such as the F9P (i.e. NMEA, UBX or RTCM3), so - as I say - errors of this kind are normally associated with a corrupt serial stream (e.g. incorrect baud rate or some other process interfering with the stream).

Are you happy for me to close this issue in relation to the web server example? If you continue to get persistent 'UNKNOWN PROTOCOL' errors from `pyubx2` elsewhere then by all means raise a separate issue. Cheers.

**Comment by foxittt** [comment]
Hello
Is it possible to make such webserver example for pyrtcm + ntrip?

**Comment by semuadmin** [comment]
Hi @foxittt. The intention with this example is to wrap a simple HTTP server around the parsed serial data stream from a local GNSS device. For simplicity sake it currently only parses selected UBX messages, but could easily be modified to parse NMEA and/or RTCM3 messages coming from the same device.

NTRIP, on the other hand, is already an internet-based protocol so much of this would be superfluous. You can access any (public) NTRIP caster by simply opening the appropriate URL in any web browser (e.g. http://rtk2go.com:2101), though you obviously wouldn't get the parsed RTCM3 data without further client-side processing. 

Have a look at `ntrip_handler.py` in `PyGPSClient` for an illustration of how to receive and parse an NTRIP data stream: https://github.com/semuconsulting/PyGPSClient/blob/master/pygpsclient/ntrip_handler.py

**Comment by foxittt** [comment]
Thanks! I`ll try.

**Comment by semuadmin** [comment]
Hi @foxittt ,

FYI This is typical output from an NTRIP caster as output by the PyGPSClient utility - is this the sort of thing you were looking to see?

<img width="1440" alt="Screenshot 2022-04-12 at 11 45 31" src="https://user-images.githubusercontent.com/28569967/162943560-bd929a47-dc16-47e6-8cad-94a4486bd3b1.png">

**Comment by foxittt** [comment]
Yes.
