### ISSUE TITLE
tcp input instead of serial

### ISSUE THREAD

**Issue by jancelin** [semuconsulting/pyubx2#67]
Hello,

Is it possible to use pyubx2 with a tcp input instead of serial?

My applications already use the serial port as input ```str2str -in serial://ttyACM0:115200:8:n:1#ubx -out tcpsvr://:5015``` and I would like to connect pyubx2 on the localhost:5015

thanks!

**Comment by semuadmin** [comment]
Hi @jancelin Sorry, it's not currently possible and there are no plans to add this functionality in the foreseeable future.

If you're using a Posix platform, you should be able to use the standard `ser2net` and/or `socat` utilities to map a TCP socket to a serial stream or vice versa. Others have done this successfully.

As it happens, there is a similar issue on the backlog to add this functionality to the GUI application PyGPSClient (https://github.com/semuconsulting/PyGPSClient/issues/18), but I have no timeframe on this at present.

**Comment by jancelin** [comment]
Ok 
thanks for the explanation

**Comment by semuadmin** [comment]
Hi @jancelin 

If you don't mind I'd actually like to keep this open for now, as it's a reasonable feature request. Just not sure when I'll have the time to implement. 

It would probably be very simple in the first instance (i.e. no encryption or authentication) but I may look to offer enhanced functionalty at a later date.
