### ISSUE TITLE
NAV-PVT via I2C?

### ISSUE THREAD

**Issue by robomike** [semuconsulting/pyubx2#83]
Is there an example on how to poll the  NAV-PVT message via I2C ?

**Comment by semuadmin** [comment]
Hi @robomike No, not explicitly.  But if you already have working I2C connectivity then it's the same UBX poll commands as if you were using USB or UART. See existing Serial examples.

**Comment by robomike** [comment]
Hi @semuadmin thank you for the response.  How do I set the i2c port and address for ubxpoller to get that NAV-PVT message?  I only see an example for UART, I'm on ubuntu with a jetson

**Comment by semuadmin** [comment]
These utilities don't directly support I2C connectivity, just Serial (USB/UART). You'd have to engineer an I2C connection yourself. There are Python I2C libraries available - try a search on StackOverflow etc.
