### ISSUE TITLE
Parsing .ubx files

### ISSUE THREAD

**Issue by fener1efes2** [semuconsulting/pyubx2#89]
I have created a .ubx file by using u-center with ZED-F9P and NEO-6M.
I just want to extract information like C/No values of the satellites or AGC count from .ubx file created by u-center.
Am I able to do that with this repo?

**Comment by semuadmin** [comment]
Hi @fener1efes2 ,

Yes, absolutely. The .ubx files created by u-center are simply files containing raw (binary) data from the GNSS device (including NMEA, UBX and/or RTCM protocols, depending on what the device is configured to output). Note that .ubx files may also contain proprietary UBX diagnostic and configuration data which the u-blox technical support team can use for testing and problem investigation.

You could for example use the `ubxfile.py` example in the `/examples` folder, or write something similar yourself.

https://github.com/semuconsulting/pyubx2/blob/master/examples/ubxfile.py

Alternatively you could use the `gnssdump` CLI utility which is installed with the `pygnssutils` library. This is essentially a CLI wrapper around the pyubx2 parser which offers a variety of formatting and filtering options.

https://github.com/semuconsulting/pygnssutils#gnssdump

for help at the command line, type `gnssdump -h`

Hope this helps
